services:
  nginx:
    image: nginx:latest
    container_name: lemp_nginx
    ports:
      - "4001:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: lemp_php
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: lemp_mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: testdb
    secrets:
      - db_root_password
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lemp_phpmyadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

secrets:
  db_root_password:
    file: db_root_password.txt
